name: app_music
description: "NOVA MUSIC - Simple Music Player App for Flutter Learning"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # just_audio: package untuk memutar audio lokal (MP3, AAC, dll.)
  # Install: flutter pub add just_audio
  # Dokumentasi: https://pub.dev/packages/just_audio
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Daftarkan folder assets di sini agar Flutter bisa membacanya
  assets:
    - assets/images/
    - assets/audio/
